import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import api, { messageFrom } from '../../services/api';

export default function ForgotPassword() {
  const [step, setStep] = useState(1), [form, setForm] = useState({ email: '', otp: '', password: '' }), [loading, setLoading] = useState(false); const navigate = useNavigate();
  const submit = async event => { event.preventDefault(); setLoading(true); try { if (step === 1) { const { data } = await api.post('/auth/password/forgot', { email: form.email }); setStep(2); toast.success(data.devOtp ? `Development OTP: ${data.devOtp}` : data.message, { duration: 7000 }); } else { await api.post('/auth/password/reset', form); toast.success('Password reset successfully'); navigate('/login'); } } catch (error) { toast.error(messageFrom(error)); } finally { setLoading(false); } };
  return <div><p className="text-xs font-bold uppercase tracking-[.2em] text-primary-600">Account recovery</p><h2 className="mt-2 text-3xl font-extrabold">Reset your password</h2><p className="mt-2 text-sm text-slate-500">{step === 1 ? 'We’ll email you a secure reset code.' : 'Enter the code and choose a new password.'}</p><form onSubmit={submit} className="mt-6 space-y-4"><label><span className="label">Email address</span><input required type="email" className="field" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })}/></label>{step === 2 && <><label><span className="label">Reset code</span><input required maxLength="6" className="field" value={form.otp} onChange={e => setForm({ ...form, otp: e.target.value })}/></label><label><span className="label">New password</span><input required minLength="8" type="password" className="field" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })}/></label></>}<button disabled={loading} className="btn-primary w-full">{loading ? 'Please wait…' : step === 1 ? 'Send reset code' : 'Reset password'}</button></form><Link to="/login" className="mt-5 block text-center text-sm font-bold text-primary-600">Back to sign in</Link></div>;
}
