import { Router } from 'express';
import * as exams from '../controllers/examController.js';
import * as questions from '../controllers/questionController.js';
import * as attempts from '../controllers/attemptController.js';
import { protect, authorize } from '../middlewares/auth.js';
import { validate } from '../middlewares/validate.js';
import { upload } from '../middlewares/upload.js';
import { examRules, questionRules } from '../validators/examValidators.js';
const router = Router(); router.use(protect);
router.get('/', exams.listExams); router.get('/code/:code', exams.getExam);
router.post('/', authorize('admin'), examRules, validate, exams.createExam);
router.route('/:id').get(exams.getExam).patch(authorize('admin'), examRules, validate, exams.updateExam).delete(authorize('admin'), exams.deleteExam);
router.post('/:id/deploy', authorize('admin'), exams.deployExam); router.post('/:id/close', authorize('admin'), exams.closeExam);
router.route('/:examId/questions').get(authorize('admin'), questions.listQuestions).post(authorize('admin'), upload.single('image'), questionRules, validate, questions.createQuestion);
router.post('/:examId/questions/bulk', authorize('admin'), questions.bulkQuestions);
router.route('/questions/:id').patch(authorize('admin'), questions.updateQuestion).delete(authorize('admin'), questions.deleteQuestion);
router.post('/attempts/start/:code', authorize('student'), attempts.startAttempt);
router.post('/attempts/:id/warning', authorize('student'), attempts.registerWarning);
router.post('/attempts/:id/submit', authorize('student'), attempts.submitAttempt);
export default router;
